config/routes.rb
Rails.application.routes.draw do
	# get 'containers/missed', to: 'missed_bins#show'
  resources :containers
  resources :services

  get 'missed-containers', to: 'missed_bins#show'

  # resource 'missed_bin'

  root to: 'visitors#index'

  get 'styleguide', to: 'visitors#styleguide'
  get 'landingpage', to: 'visitors#landingpage'
end

app/models/MissedCollectionReport.rb
class MissedCollectionReport
  
end

app/models/collection.rb
class Collection
  include Her::Model
end

app/models/container.rb
class Container < ActiveRecord::Base
end

app/models/container_type.rb
class ContainerType
  include Her::Model
  has_many :material_streams
end

app/models/mapit/postcode.rb
module Mapit
  class Postcode
    include Her::Model
    # collection_path "/postcode/:id"
    collection_path "/postcode"

  end
end

app/models/material_stream.rb
class MaterialStream
  include Her::Model
end

app/models/service.rb
class Service
  include Her::Model
  has_one :last_collection, class_name: "Collection"
  has_one :next_collection, class_name: "Collection"
  has_many :container_types
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/containers_controller.rb
class ContainersController < ApplicationController
  before_action :set_container, only: [:show, :edit, :update, :destroy]

  # GET /containers
  # GET /containers.json
  def index
    @containers = Container.all
  end

  # GET /containers/1
  # GET /containers/1.json
  def show
  end

  # GET /containers/new
  def new
    @container = Container.new
  end

  # GET /containers/1/edit
  def edit
  end

  # POST /containers
  # POST /containers.json
  def create
    @container = Container.new(container_params)

    respond_to do |format|
      if @container.save
        format.html { redirect_to @container, notice: 'Container was successfully created.' }
        format.json { render :show, status: :created, location: @container }
      else
        format.html { render :new }
        format.json { render json: @container.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /containers/1
  # PATCH/PUT /containers/1.json
  def update
    respond_to do |format|
      if @container.update(container_params)
        format.html { redirect_to @container, notice: 'Container was successfully updated.' }
        format.json { render :show, status: :ok, location: @container }
      else
        format.html { render :edit }
        format.json { render json: @container.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /containers/1
  # DELETE /containers/1.json
  def destroy
    @container.destroy
    respond_to do |format|
      format.html { redirect_to containers_url, notice: 'Container was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_container
      @container = Container.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def container_params
      params.require(:container).permit(:color)
    end
end

app/controllers/missed_bins_controller.rb
# require 'wicked'

class MissedBinsController < ApplicationController
  include Wicked::Wizard

  add_breadcrumb "Home", :root_path
  add_breadcrumb "Waste and Recycling", :root_path
  
  steps :find_address, :select_bins, :personal_details, :finish

  def show
    puts wizard_path(:select_bins)
    case step
    when :select_bins
      @services = Service.all
      # @service = @services[0]
    end

    render_wizard
  end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  def index
    puts 'index'
    @services = Service.all
    puts @services.to_yaml
  end
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
  add_breadcrumb "Home", :root_path
end

app/helpers/application_helper.rb
module ApplicationHelper
  def formatted_date(date)
    Time.xmlschema(date).strftime("%d %B %Y")
  end
end

app/helpers/containers_helper.rb
module ContainersHelper
end

app/helpers/missed_bin_helper.rb
module MissedBinHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/containers/_form.html.haml
= simple_form_for(@container) do |f|
  = f.error_notification

  .form-inputs
    = f.input :color

  .form-actions
    = f.button :submit

app/views/containers/edit.html.haml
%h1 Editing container

= render 'form'

= link_to 'Show', @container
\|
= link_to 'Back', containers_path

app/views/containers/index.html.haml
%h1 Listing containers

%table
  %thead
    %tr
      %th Color
      %th
      %th
      %th

  %tbody
    - @containers.each do |container|
      %tr
        %td= container.color
        %td= link_to 'Show', container
        %td= link_to 'Edit', edit_container_path(container)
        %td= link_to 'Destroy', container, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Container', new_container_path

app/views/containers/missed/select.html.haml
%h3 Select

 

app/views/containers/new.html.haml
%h1 New container

= render 'form'

= link_to 'Back', containers_path

app/views/containers/show.html.haml
%p#notice= notice

%p
  %b Color:
  = @container.color

= link_to 'Edit', edit_container_path(@container)
\|
= link_to 'Back', containers_path

app/views/layouts/_breadcrumbs.html.haml
%ol.breadcrumbs
  = render_breadcrumbs :tag => :li, :separator => ' '

app/views/layouts/_messages.html.haml
-# Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
%nav.top-bar{"data-topbar" => "", :role => "navigation"}
  %ul.title-area
    %li.name
      %h1
        %a{:href => "/"} My Council
    / Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone
    %li.toggle-topbar.menu-icon
      %a{:href => "/"}
        %span Menu
  %section.top-bar-section
    / Right Nav Section

    / Left Nav Section
    %ul.left
      %li
        %a{:href => "/"} Waste and Recycling
      %li
        %a{:href => "/styleguide"} Styleguide
      %li
        %a{:href => "/landingpage"} Landing page

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    %title= content_for?(:title) ? yield(:title) : 'Waste Services'
    %meta{:name => "description", :content => "#{content_for?(:description) ? yield(:description) : 'Waste Ui'}"}
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'vendor/modernizr'
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %header
      = render 'layouts/navigation'
      
    %main{:role => "main"}
      .container
        = render 'layouts/breadcrumbs'
      = render 'layouts/messages'
      = yield

app/views/missed_bins/find_address.html.haml
.container
  %h2 Find your address

  = label_tag(:address_search, "Enter a postcode:")
  .input-group
    = text_field_tag(:address_search, nil, class: "form-control")
    %span.input-group-btn
      = link_to 'Search', nil, {"class" =>"btn btn-primary"}

  %p Choose your address:
  .list-group
    %button.list-group-item{"type"=>"button"} 20 Acacia Avenue, Anytown, AB1 2CD
    %button.list-group-item{"type"=>"button"} 22 Acacia Avenue, Anytown, AB1 2CD
    %button.list-group-item{"type"=>"button"} 24 Acacia Avenue, Anytown, AB1 2CD
    %button.list-group-item{"type"=>"button"} 26 Acacia Avenue, Anytown, AB1 2CD


  = link_to 'Next', next_wizard_path, {"class" =>"btn btn-primary"}

app/views/missed_bins/finish.html.haml
.container
  %h2 Thank you for your report

  

app/views/missed_bins/personal_details.html.haml
.container
  %h2 Enter your details

  %p Please provide your contact details so that we can get in touch about next steps.

  .field
    = label_tag(:name, "Name:")
    = text_field_tag(:name, nil, class: "form-control")

  .field
    = label_tag(:telephone, "Telephone number:")
    = text_field_tag(:telephone, nil, class: "form-control")

  .field
    = label_tag(:email, "Email:")
    = text_field_tag(:email, nil, class: "form-control")

  = link_to 'Next', next_wizard_path, {"class" =>"btn btn-primary"}

app/views/missed_bins/select_bins.html.haml
.container
  %h2 Latest collections

  %p Did we miss your bins? Check for issues we already know about or add a new issue.

  %p Please select the containers that have not been collected. Make sure to review any reported issues with the collection before submitting a report.

  / # = form_tag(next_wizard_path, method: "get") do
  - @services.each do |service|
    .panel.panel-info
      .panel-heading
        %h2.panel-title= service.name
      .panel-body
        - if service['next_collection']
          .res-label Next collection
          .collection-date= formatted_date(service.next_collection.date)
        - if service['last_collection']
          .res-label Last collection
          .collection-date= formatted_date(service.last_collection.date)
          %h4 Events
          - service.last_collection.events.each do |event|
            %p= event['type']
            %img.pull-left{"src"=>"#{event['image']}"}

      %ul.list-group

        - service.container_types.each do |container|
          %li.list-group-item
            .checkbox.lg.pull-right
              %label
                = check_box_tag(:container)
            %h4.container-name
              = container.description
            - container.material_streams.each do |material_stream|
              %span.material-stream
                = material_stream.name

            - if service['events']
              %ul.list-group
                - service.events.each do |event|
                  - if event.container_color == container.color
                    %li.list-group-item.list-group-item-danger
                      %span.glyphicon.glyphicon-exclamation-sign
                      .event-type= event.type



  = link_to 'Back', previous_wizard_path, {"class" =>"btn btn-default"}
  = link_to 'Report missed collection', next_wizard_path, {"class" =>"btn btn-primary"}

app/views/missed_bins/show.html.haml
%h1 MissedBin#show
%p Find me in app/views/missed_bin/show.html.haml

app/views/pages/about.html.erb
<% content_for :title do %>About<% end %>
<h3>About the Website</h3>
<p>
This web application was created with
<%= link_to('Rails Composer', 'http://railsapps.github.io/rails-composer/') %>
from the <%= link_to('RailsApps project', 'http://railsapps.github.io/') %>.
</p>

app/views/services/index.html.haml
.container
  %h1 Services

  - @services.each do |service|
    .panel.panel-info
      .panel-heading
        .panel-title= service.name
      .panel-body

    /= service.provider['name']

app/views/visitors/index.html.haml
- titles = ['Schools', 'Transport and streets', 'Council tax', 'Social care', 'Elections']

.row
  .columns.small-12
    %h1 Home

    - titles.each do |t|
      .panel.panel-info.panel-services
        .panel-heading
          .panel-title= t
        .panel-body
          %a{:href => '/#'} Link 1
          %br
          %a{:href => '/#'} Link 2
          %br
          %a{:href => '/#'} Link 3
          %br

    .panel.panel-info.panel-services
      .panel-heading
        .panel-title Waste and recycling
      .panel-body
        %a{:href => '/services'} Collection services
        %br
        %a{:href => '/missed-containers?id=find_address'} Report a missed bin
        %br
        %a{:href => '/#'} A-Z 
        %br

app/views/visitors/landingpage.html.haml
.container
  .row
    .small-12.medium-8.large-8.column
      %h1 Rubbish and recycling
  .row
    .small-12.medium-2.column
      .ul.side-nav
        %li
          %a{:href => "#{}"} Home
        %li
          %a{:href => "#{}"} Benefits
        %li
          %a{:href => "#{}"} Business
        %li
          %a{:href => "#{}"} Community & living
        %li
          %a{:href => "#{}"} Council & democracy
        %li
          %a{:href => "#{}"} Council tax
        %li
          %a{:href => "#{}"} Education & learning
        %li.active
          %a Environment & planning
        %li
          %a{:href => "#{}"} Health & social care
        %li
          %a{:href => "#{}"} Housing
        %li
          %a{:href => "#{}"} Jobs & careers
        %li
          %a{:href => "#{}"} Leisure & culture
        %li
          %a{:href => "#{}"} Transport & streets
    .small-12.medium-10.column
      .panel.panel-postcode
        %h3 Tell us where you live
        %p Enter your postcode then choose your property from the dropdown list
        %form
          .large-12.columns
            .row.collapse
              .small-10.columns
                %input{:placeholder => "Your post code", :type => "text"}/
              .small-2.columns
                %a.button.postfix{:href => "#"} Go
          %input#no-click-me{:name => "address-cookie", :type => "checkbox"}/
          %label{:for => "no-click-me"}
            Save this in a cookie as My address
            %a{:href => "#{}"} Learn more about cookies
      %ul.small-block-grid-3{"data-equalizer" => ""}
        %li
          %a{:href => "#{}"}
            .panel{"data-equalizer-watch" => ""}
              %strong Collection times
              .small Use our locator to find your next collection day
        %li
          %a{:href => "#{}"}
            .panel{"data-equalizer-watch" => ""}
              %strong Missed collections
              .small Report a missed collection and discover reasons why your bins may not have been collected this week
        %li
          %a{:href => "#{}"}
            .panel{"data-equalizer-watch" => ""}
              %strong Reducing waste
              .small We're ranked 13 in the country for recycling. Learn how we can become number one!

      %ul.small-block-grid-4
        %li
          %a{:href => "#{}"}
            %strong Your responsibilities
          %p Learn more about where to leave your bins, when to bring them in, how to fill them and how to avoid contamination and missed collections.
        %li
          %a{:href => "#{}"}
            %strong Download or print a calendar
          %p Pin our collection schedule to your fridge door to help you to always know when to leave your bins out for collection
        %li
          %a{:href => "#{}"}
            %strong Forgotten to leave your bins out?
          %p If you've accidentally missed a collection, here's what you can do.
        %li
          %a{:href => "#{}"}
            %strong Donating clothes and textiles
          %p We do not take textiles in our weekly collections but here are some locations where you can drop off clothing and textiles.
        %li
          %a{:href => "#{}"}
            %strong Special collections for large items
          %p If you have a bulky item or white goods which you no longer need, arrange for our Bulky Collections team to come and pick them up.
        %li
          %a{:href => "#{}"}
            %strong Commercial waste
          %p Read more about Commercial Waste an recycling for businesses.
        %li
          %a{:href => "#{}"}
            %strong Report fly tipping and graffiti
          %p If you have spotted any on buildings or property in the area.
        %li
          %a{:href => "#{}"}
            %strong Assisted collections
          %p If you are sick, infirm or a carer for someone who is unable to take their bins out each week, apply for an Assisted Collection here

    .small-12.medium-10.column
      .panel.panel-outer
        %h2 Contact your waste team
        %p
          %strong Recycling manager
          %br/
          Central Depot, Mytown, Mycounty, AB1 2CD
          %br/
          Tel: 01234 567 890
          %br/
          Email: wasteservices@mycouncil.gov.uk